### PR TITLE
Include jFirm in the Project

### PR DESCRIPTION
**Pull request by Schaback**
This should work for everyone, but actually _using_ the command will lead to runtime errors if the dynamic linker can't find the libfirm library.

### CODE REVIEW

**Comment by I-Al-Istannen** [comment]
We have a fork of jFirm https://github.com/firmwehr/jFirm that includes the linux .so (and maybe mac, but not windows at the moment as getting that to build is probably futile) in case you want to bundle it. Something like
```kt
implementation("net.java.dev.jna:jna:4.5.2")
implementation("com.github.Firmwehr:jFirm:b970d57751")
```
should suffice to get it running, *if* you set the firm version to some useful value before calling Firm.init, e.g.
```java
	static {
		// Must be set before Firm.init is called!
		Firm.VERSION = Firm.FirmVersion.DEBUG;
	}
```
If you set the `Firm.VERSION` to `FIRM` (which is the default if you do not change it), it will look for a `libfirm.so` on your system, just the way it currently works. If you set it to DEBUG or RELEASE, it will use a bundled DEBUG/RELEASE build (linked against GLIBC 2.29 I think) without you needing to do anything else.

Just though I'd mention it before there are multiple versions of it around :)

You can also decide not to ship the dynamically linked binary but then you need some way to download/build it at runtime, if I am not mistaken.

**Comment by Schaback** [comment]
@I-Al-Istannen 
> You can also decide not to ship the dynamically linked binary but then you need some way to download/build it at runtime, if I am not mistaken.

Thanks for the heads-up.

I remember them saying something about a pre-build libfirm.so being available on all systems this needs to run on, ready to link against (in the system's library search path).
Therefore we haven't bothered with any of that, am I misremembering?
Platform-independent builds of FIRM are a PITA, so we went "----skip-----" at the first opportunity to do so. :)

**Comment by I-Al-Istannen** [comment]
Maybe they did, it's just a bit more cumbersome for contributors, users and continuous integration. By the looks of it you aren't doing that at all though, so it is unlikely you will run into problems.

I will have to think about what I do with the mjtest-tests gitlab CI for your group then. I can probably build a debug build of libfirm inside the docker image and move it to /usr/lib or sth. That won't be awesome but might work. I'll have a look after the PRs are merged and I can watch your compiler crash and toy around with it a bit.

**Comment by Schaback** [comment]
We can also switch to shipping pre-builts if the other groups are doing it and it is such a hassle.
We decided not to originally, as some of our members where using windows without wsl to start of on. They since have switched to WSL as far as I know, so this is no longer a blocker.

**Comment by I-Al-Istannen** [comment]
I am fine with both, I will just have a look at what works after the PRs are merged and fix things up. I don't doubt that I will get that to work for all groups with a limited amount of work :) The problem isn't really complex if you control the execution environment (famous last words, I know :P)

You do not need to change anything, if you have already set up local working environments for all members.

**Pull request merged**
